### ISSUE TITLE
When I install this plugin, all rems' font are changed, even if they have not any tags.

### ISSUE THREAD

**Issue by dreamness-dnalm** [mzguntalan/rem-tex#1]
Hi, I like this plugin, it's pretty.  
When I install this plugin, all rems' fonts are changed, even if they don't have any tags.
Thank you.

**Comment by mzguntalan** [comment]
Thank you. That was the intended behavior (make rems look like LaTeX), then the tags just add to it, since I personally prefer to make my notes look like a LaTeX 😅 . Please see the pictures labeled Default at the README for the intended behavior (without tags).

However, if you just want the ##LaTeX Style just on the rems tagged with it, you can paste the following in your custom CSS

```CSS
.rem-text {
	font-family: inherit;
	font-size: 1em;
} 

.document-title {
	font-family: inherit;
	font-size: 1.5em;
	border-style: solid;
	border-color: #a2a9b1;
	border-width: 0px 0px 1px 0px;
	margin-bottom: 8px;
} 
	
[data-rem-container-tags~=latex-style] .rem-text  {
	font-family: "CMU Serif", "Times New Roman", Serif;
	font-size: 1em;
}

[data-document-tags~=latex-style] .document-title  {
	font-family: "CMU Serif", "Times New Roman", Serif;
}
```

Happy Noting 😁.
